version: '3.8'

services:
  daraja-app:
    container_name: daraja
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - daraja-network

networks:
  daraja-network:
    driver: bridge
